version: '2'
services:
  db:
    image: linuxserver/mariadb
    volumes:
      - ./db_config:/config
    environment:
      MYSQL_ROOT_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build: .
    links:
      - db
    volumes:
      - ./wp_config:/config
    ports:
      - "80:80"
      - "443:443"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress