#!/bin/sh

chown -R abc:abc /var/log/hhvm
chown -R abc:abc /var/run/hhvm
rm rm -rf /var/run/hhvm/*
cd /config/www/wordpress
exec /sbin/setuser abc hhvm --mode server -c /etc/hhvm/server.ini -d hhvm.server.type=fastcgi -d hhvm.server.file_socket=/var/run/hhvm/hhvm.sock -d hhvm.server.fix_path_info=true