#!/usr/bin/with-contenv bash

cd /config/www/wordpress || exit

chown -R abc:abc /var/log/hhvm
chown -R abc:abc /var/run/hhvm
rm rm -rf /var/run/hhvm/

exec s6-setuidgid abc hhvm --mode server -c /etc/hhvm/server.ini -d hhvm.server.type=fastcgi -d hhvm.server.fix_path_info=true
